import "./globals.css";
import Navbar2 from "./components/Navbar2";
import Footer from "./components/Footer";

export const metadata = {
  title: "CRM Hizmetleri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar2 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
